#-------------------------------------------------------------------------------------------
# Copyright (c) 2026-present, SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

[package]
name = "shell"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
async-select = "0.3"
futures-util = "0.3"
gtk4-layer-shell = "0.8"
relm4 = "0.11"
relm4-components = "0.11"
tokio-util = "0.7"
zbus = "5.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
